spring.application.name=coconut-management
spring.datasource.url=jdbc:mysql://localhost:3306/coconut_db
spring.datasource.username=root
spring.datasource.password=Mohan2003.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080