spring.application.name=coconut-management
spring.datasource.url=jdbc:mysql://coconut-management123-mohanprasanthd01-e1fe.f.aivencloud.com:20177/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_GmwgO9VxHiWhSFICDep

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
